# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
       - name: Get branch name
         id: get-branch
         uses: xom9ikk/split@v1
         with:
            string: ${{ github.ref }}
            separator: refs/heads/
       - name: Msg
       - run: |
            echo "Log: ${{ steps.get-branch.outputs._1 }}"
        
